# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Remindify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Remindify
  pod 'YNExpandableCell'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'DateTimePicker'
end
